"""Event-aware directed-structure analysis for calcium transients."""

from .calibration import (
    ThresholdCalibrationResult,
    calibrate_roi_thresholds,
    calibration_signal,
)
from .baselines import (
    LPCMCIAdapter,
    LPCMCIResult,
    OASISDeconvolver,
    OASISResult,
    project_lossy_lagged_pag_skeleton,
)

from .diagnostics import (
    ResidualDiagnostics,
    TransientSummary,
    characterize_transients,
    residual_diagnostics,
)
from .comparison import (
    add_paired_deltas,
    graph_summary,
    positions_from_mid,
    sides_from_mid,
    summarize_adjacency_cache,
    write_summary_csv,
)
from .estimators import (
    CausalisedGC,
    GraphResult,
    RiseFlankCandidateMatch,
    RiseFlankCandidateResult,
    RiseFlankRunSummary,
    benjamini_hochberg,
    extract_rise_flank_runs,
    finite_sample_permutation_p_values,
    match_shifted_rise_flank_runs,
    rise_flank_candidate_pairs,
    selected_frame_indices,
    weighted_benjamini_hochberg,
)
from .metrics import delta_w_ic, edge_recovery, graph_stability, w_ic, w_rc
from .onset_detection import (
    BayesianOnsetResult,
    ChangePointOnsetResult,
    detect_bayesian_onsets,
    detect_change_point_onsets,
)
from .pipeline import AnalysisConfig, PipelineResult, run_pipeline
from .plotting import (
    plot_directed_graph,
    plot_matrix,
    plot_topographic_graph,
    plot_topographic_pair,
)
from .preprocessing import ScenarioData, build_scenarios
from .representations import RepresentationBundle, build_representations, rising_flank
from .robustness import (
    SensitivityRun,
    SyntheticCondition,
    SyntheticGridRun,
    downsample_dataset,
    run_analysis_sensitivity,
    run_synthetic_grid,
    split_calibration_evaluation,
)
from .sensitivity import PartialAncestralGraph, run_latent_confounding_sensitivity
from .temporal_priors import (
    TemporalPriorResult,
    TemporalPriorStateMasks,
    build_temporal_prior,
    temporal_prior_state_masks,
)
from .validation import (
    DynamicSimulationConfig,
    EventNullControlResult,
    StabilityResult,
    SyntheticDataset,
    SyntheticEpisode,
    bootstrap_event_indices,
    cross_recording_surrogate,
    jitter_event_indices,
    permute_phase_event_indices,
    reverse_event_indices,
    run_event_bootstrap_stability,
    run_event_null_controls,
    run_leave_one_neuron_stability,
    run_leave_one_transient_stability,
    run_null_controls,
    run_time_window_stability,
    simulate_calcium_dataset,
    validate_representations,
)

__all__ = [
    "AnalysisConfig",
    "BayesianOnsetResult",
    "CausalisedGC",
    "ChangePointOnsetResult",
    "DynamicSimulationConfig",
    "EventNullControlResult",
    "GraphResult",
    "LPCMCIAdapter",
    "LPCMCIResult",
    "OASISDeconvolver",
    "OASISResult",
    "PartialAncestralGraph",
    "PipelineResult",
    "ResidualDiagnostics",
    "RepresentationBundle",
    "RiseFlankCandidateMatch",
    "RiseFlankCandidateResult",
    "RiseFlankRunSummary",
    "ScenarioData",
    "SensitivityRun",
    "StabilityResult",
    "SyntheticCondition",
    "SyntheticDataset",
    "SyntheticEpisode",
    "SyntheticGridRun",
    "TemporalPriorResult",
    "TemporalPriorStateMasks",
    "ThresholdCalibrationResult",
    "TransientSummary",
    "add_paired_deltas",
    "build_representations",
    "build_scenarios",
    "build_temporal_prior",
    "calibrate_roi_thresholds",
    "calibration_signal",
    "bootstrap_event_indices",
    "characterize_transients",
    "cross_recording_surrogate",
    "delta_w_ic",
    "detect_bayesian_onsets",
    "detect_change_point_onsets",
    "downsample_dataset",
    "edge_recovery",
    "extract_rise_flank_runs",
    "finite_sample_permutation_p_values",
    "graph_stability",
    "graph_summary",
    "jitter_event_indices",
    "match_shifted_rise_flank_runs",
    "permute_phase_event_indices",
    "positions_from_mid",
    "plot_directed_graph",
    "plot_matrix",
    "plot_topographic_graph",
    "plot_topographic_pair",
    "project_lossy_lagged_pag_skeleton",
    "residual_diagnostics",
    "reverse_event_indices",
    "rising_flank",
    "rise_flank_candidate_pairs",
    "run_analysis_sensitivity",
    "run_event_bootstrap_stability",
    "run_event_null_controls",
    "run_latent_confounding_sensitivity",
    "run_leave_one_neuron_stability",
    "run_leave_one_transient_stability",
    "run_pipeline",
    "run_null_controls",
    "run_synthetic_grid",
    "run_time_window_stability",
    "selected_frame_indices",
    "simulate_calcium_dataset",
    "sides_from_mid",
    "split_calibration_evaluation",
    "summarize_adjacency_cache",
    "temporal_prior_state_masks",
    "validate_representations",
    "weighted_benjamini_hochberg",
    "benjamini_hochberg",
    "w_ic",
    "w_rc",
    "write_summary_csv",
]
